---
Name: cloudflare_extensions
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'Symbiote\Cloudflare\SiteTreeExtension'

SilverStripe\Assets\File:
  extensions:
    - 'Symbiote\Cloudflare\FileExtension'

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - 'WebbuildersGroup\Cloudflare\Extensions\BaseElementExtension'
