---
Name: cloudflare_extensions
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'Symbiote\Cloudflare\SiteTreeExtension'

SilverStripe\Assets\File:
  extensions:
    - 'Symbiote\Cloudflare\FileExtension'

---
Name: cloudflare_extensions_elemental
Only:
  moduleexists: 'dnadesign/silverstripe-elemental'
---
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - 'WebbuildersGroup\Cloudflare\Extensions\BaseElementExtension'
